### PR TITLE
circumvents a compilation problem with alpha version of Coq 8.20

### PR DESCRIPTION
**Pull request by rmatthes**
The changes happen in an "abstract" part and should therefore not have an impact on execution times later.

Currently set as draft PR since I can maybe address the second compilation problem CI is reporting these days as well.

### CODE REVIEW

**Comment by rmatthes** [comment]
I tried it with Coq dev of yesterday afternoon (commit b3ce0023). Hopefully, CI Coq dev approves it as well.

**Comment by rmatthes** [comment]
another compilation error was revealed beyond the two already dealt with in this PR

**Comment by benediktahrens** [comment]
I am not sure whether to merge this PR is a good idea. Ideally, something that worked in Coq in 8.18 will also work in 8.20. It could help the Coq devs to understand how to make the code compile in 8.20, hence pointing them to this PR could be useful. The Coq issue is here: https://github.com/coq/coq/issues/18593

**Comment by rmatthes** [comment]
If CI succeeds this time, we would at least know about all the regression problems currently coming from Coq 8.20. One time, the fix is to use "use" in place of "apply" - this is still a regression. All the other problems are with rewriting with `pr1_transportf`. I failed to see how this works with more provided arguments, and I resorted to apply/refine.

I put this PR on hold.

**Comment by nmvdw** [comment]
With https://github.com/UniMath/UniMath/pull/1850, I am becoming in favor of merging this PR. Once #1850 gets merged and once the Coq PR corresponding to #1850 is merged, it will become necessary to add `#[reversible]` to our coercions to prevent an error with Coq dev. However, there is no way people (like me) will remember to do that consistently without an error from Coq dev.

**Comment by proux01** [comment]
Well, you would need to add `#[reversible]` if you use it. Before 8.16, reversible coercions did not exist, so surely Unimath did not depend on them. When they were introduced, it was expected that `Coercion` kept not introducing reversible coercions (i.e., `Coercion` should have been `#[reversible=no] Coercion`). Unfortunately, due to a bug, reversible coercions became the default when typing `Coercion`. Unimath then started depending on it, but I have no idea if this is intentional and what's the extent of that dependency. #1850 is just a way to preserve the current behavior so that the fix in Coq does not break Unimath, it may or may not be what you want in the long run.

**Comment by rmatthes** [comment]
Is there a hope that the problem the present PR fixes might be caused by lacking reversible coercions?

**Comment by proux01** [comment]
No, except if you explicitly declared some coercion non reversible, since currently all coercions are reversible by default.

**Comment by nmvdw** [comment]
> o_O, still not done:
> 
> ```
>           coqc UniMath/Bicategories/ComprehensionCat/TypeFormers/Democracy.{glob,vo} (exit 1)
>   File "./UniMath/Bicategories/ComprehensionCat/TypeFormers/Democracy.v", line 225, characters 8-35:
>   Error:
>   Found no subterm matching "pr1 (transportf (mor_disp ?M80 ?M81) ?M84 ?M85)" in the current goal.
> ```

This was caused by a recent PR, meaning that errors might be introduced in later PRs as well.

**Comment by benediktahrens** [comment]
@rmatthes @nmvdw : how about we merge this PR now and fix the remaining errors in a subsequent PR?

**Comment by nmvdw** [comment]
> @rmatthes @nmvdw : how about we merge this PR now and fix the remaining errors in a subsequent PR?

Yes.

**Comment by rmatthes** [comment]
Fine with me.
